imports:
    - { resource: parameters.yml }
    - { resource: config_sonata.yml }
    - { resource: config_monolog.yml }
    - { resource: security.yml }
    - { resource: services.yml }



# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    site_name: 'Base SF2'

    web_directory_name: webroot/web
    path_to_upload_dir: ../data/uploads
    liip_imagine.resolvers.default.web_path.cache_prefix: media/cache

    router.request_context.host: %site_domain%
    router.request_context.scheme: http
    knp.doctrine_behaviors.blameable_subscriber.user_entity: CoreBundle\Entity\User

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'AdminBundle:Form:elfinderTheme.html.twig'
        - 'AdminBundle:Form:plainFieldsTheme.html.twig'
        - 'AdminBundle:Form:jsonEditorTheme.html.twig'
        - 'SonataCoreBundle:Form:datepicker.html.twig'
    globals:
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
          json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    port:      "%mailer_port%"


fos_user:
    db_driver: orm
    firewall_name: main
    user_class: CoreBundle\Entity\User
    from_email:
          address: %mail_from%
          sender_name : %site_name%
#    registration:
#            form:
#                type: form_registration
#    service:
#        mailer: fos_user.mailer.twig_swift
#    resetting:
#         email:
#             template:   IceCommonBundle:Mail:resetting.html.twig

# CKEditor configuration
ivory_ck_editor:
    default_config: backend_config
    configs:
        backend_config:
            allowedContent: true
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters:
                instance: ckeditor
            toolbar:
                0 : [ "Source" ]
                1 : [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ]
                2 : [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ]
                3 : [ 'Bold', 'Italic', 'Subscript', 'Superscript', '-', 'RemoveFormat' ]
                4 : [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl' ]
                5 : [ 'Link', 'Unlink', 'Anchor' ]
                6 : [ 'Image', 'Table', 'HorizontalRule', 'SpecialChar' ]
                7 : [ 'Format', 'FontSize']
                8 : [ 'TextColor' ,  'BGColor' ]
                9 : [ 'Maximize', 'ShowBlocks' ]
                10 : [ 'About' ]

#ELfinder bundle
fm_elfinder:
    instances:
        ckeditor:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/ckeditor
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'image/gif']
                        upload_deny: ['all']
                        upload_max_size: 2M