security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    acl:
        connection: default
    role_hierarchy:

        ROLE_SONATA_ADMIN:
          - ROLE_USER
        ROLE_ADMIN:
          - ROLE_SONATA_ADMIN

          - ROLE_SONATA_ADMIN_USER_LIST
          - ROLE_SONATA_ADMIN_USER_EDIT
          - ROLE_SONATA_ADMIN_USER_CREATE
          - ROLE_SONATA_ADMIN_USER_DELETE
          - ROLE_SONATA_ADMIN_USER_VIEW
          - ROLE_SONATA_ADMIN_USER_EXPORT

          - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT # if you are not using acl then this line must be uncommented
          - ROLE_SONATA_PAGE_ADMIN_BLOCK_ED

        ROLE_ADMIN_REF:
          - ROLE_SONATA_ADMIN

        ROLE_SUPER_ADMIN:
          - ROLE_ADMIN
          - ROLE_ADMIN_REF

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
                target:         /admin/login
            anonymous:          true

        # defaut login area for standard users
        main:
            switch_user:        true
            context:            user
            pattern:            .*
            form_login:
                provider:         fos_userbundle
                login_path:       /login
                use_forward:      false
                check_path:       /login_check
                failure_path:     null
#                success_handler:  ice.user.after_login_redirector
            logout:
                path:           fos_user_security_logout
                target:         /login
                handlers: ['sonata.page.cms_manager_selector']
            anonymous:          true

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin, role: [ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }